# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0002_auto_20170805_2308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
