# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0003_auto_20170805_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='generated_url',
            field=models.CharField(db_index=True, default=1234567890, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
